### ISSUE TITLE
WCA OAuth with passport in NodeJS

### ISSUE THREAD

**Issue by 0oj** [thewca/wca-oauth#3]
I'm making a node app which uses OAuth. A WCA Strategy in passport would be appropriate and very helpful for the users.

**Comment by FatBoyXPC** [comment]
I'm looking for some clarification - do you mean that you are going to implement this, or are you asking for us to implement it for you?

**Comment by jfly** [comment]
We'll gladly accept a PR adding this, else I expect someone from the WCA Software Team can add one once they need it. @coder13, did you use passport in [Fantasy cubing](https://github.com/coder13/fantasycubing)?

**Comment by coder13** [comment]
I didn't use passport for that. However, I am using passport for another
project and was actually working on just this. I can polish it up when I
have time and add it to npm.

**Comment by jfly** [comment]
OK, just to be clear, the plan for this repo is to store the code for all the code, so please commit it to this repo!

**Comment by coder13** [comment]
Will do.

**Comment by 0oj** [comment]
I am using passport for my project and would like a strategy for WCA. You have OAuth, right? How can I use it with node?

**Comment by coder13** [comment]
Hey! Just created [passport-wca](https://www.npmjs.com/package/passport-wca). I had started this code for my own express project I'm in the middle of and was also in the middle of turning this into a node package. Hope you find it useful. 

Something I forgot to mention in the readme:
The profile has a wca object. This contains all the wca specific stuff as passport likes to normalize the profile object. It has the fields `wca.id`, `wca.dob` (if you have specified the dob scope), `wca.region` (a delegate's region), `wca.senior_delegate_id` (a delegate's senior delegate's user id), `wca.teams` (this list of teams a user is part of).

You can also access raw json at profile._json like on all other passport strategies. For an example of what the user json looks like without having to go through the trouble of querying it yourself, look at https://github.com/thewca/wca-oauth/blob/master/node/passport-wca/test/data/example.json

**Comment by 0oj** [comment]
Thank you! This would really help me. But, I'm facing a problem in setting up my app on WCA. My app's on `localhost:10003` and the redirect URI would look like- `localhost:10003/auth/wca/redirect`. How can I use that? It says: 'Use `urn:ietf:wg:oauth:2.0:oob` if you want to add localhost URIs'.

**Comment by jfly** [comment]
@OojAmit, unfortunately, that message is a bit confusing. I recommend reading through https://github.com/thewca/worldcubeassociation.org/wiki/OAuth-documentation-notes to get a better sense of how this work. It has a screenshot showing how to set things up for local development.

**Comment by 0oj** [comment]
Thanks, got it to work.
